#
# Copyright (c) 2018 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymenttest
spec:
  selector:
    matchLabels:
      purpose: quota-demo
  replicas: 3
  template:
    metadata:
      annotations:
        io.kubernetes.cri-o.TrustedSandbox: "false"
        io.kubernetes.cri.untrusted-workload: "true"
      labels:
        purpose: quota-demo
    spec:
      containers:
      - name: pod-quota-demo
        image: busybox
